### ISSUE TITLE
Numbering of Module Practices

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#125]
Can these be numbered accordingly?

Module 1 Practice 1 or at least 101 Practice. 102 Practice at the top ect.

Students have no idea what practice they are doing without a disgnation at top.

**Comment by craigbeeremct** [comment]
Agreed. It would make life a lot easier when using Skillable's online labs, as their product doesn't show the numbers, just the title of the lab.

**Comment by BrianHinkelman** [comment]
Could you please elaborate? The reason labs have numbers for more backend purposes (such as to ensure the keys render in the correct order). If students can see the title of the lab (which presumably, they would know what task/scenario they are practicing) - what problem is solved by surfacing the lab number?

**Comment by pauldub64** [comment]
What are you on about here?

**Comment by craigbeeremct** [comment]
Because it is easier to say to students (either by voice or typing in chat), "Do the module 3 labs." or, "Do labs 0301, 0302 and 0303." than it is to say/type, "Do labs  Creating and Deploying Configuration Profiles, Monitor device and user activity in Intune, and Configuring Enterprise State Roaming."

The lab numbers are in Skillpipe, they should also be in the labs.

**Comment by BrianHinkelman** [comment]
Thanks, we'll take this under consideration.
