### ISSUE TITLE
New MD101T00 course Module 1 Lab 1, Exercise 3 tenant issue

### ISSUE THREAD

**Issue by joel-rosenblum** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#14]
Thank you for your assistance; perhaps I missed this detail posted elsewhere. My understanding is to proceed past this error as if it did not occur. Is that correct?

I am using the labondemand host provider, and for the instructions for Module 1 Lab 1, the host provides a global admin tenant to use for the AutoPilot deployment, but when importing the CSV file in Task 4, step 8, I receive the error "Some devices were not imported. Click here for more information." Upon clicking, I read, "Internal Error code: 806 ZtdDeviceAlreadyAssigned", but then a refresh never displays any device on the Windows Autopilot devices blade. How should I proceed?

**Comment by BrianHinkelman** [comment]
Hi Joel,

In the past the error was expected, but this is no longer the case. Typically, labs are a provisioned "copy" of pre-configured VMs - however, this process does not work for Autopilot, which needs the VM to be created "from-scratch", otherwise you would see the error you described.  In the previous version of MD-101, yes, you would skip this error, but you could not perform an end-to-end AP deployment. 

This was resolved in the updated Nov release of MD101T00 and you can now complete the AP deployment (with no error). We now provide a Hyper-V host (LON-HOST1) VM with a nested VM, LON-CL5, which is generated from scratch when the environment is launched, creating the unique VM instance Autopilot requires. 

I would open a support ticket with your lab provider. Your provider may have selected a different method for implementation, and may have different steps to perform the lab.

Regards,
Brian
