### ISSUE TITLE
0602-Configuring a WIP policy in Intune - Edge is blocked

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#45]
Task 3, 'Sync and test the WIP policy', Step 6.

I have encountered this issue for months, and despite multiple repros over that time to try and insure I am not making any mistakes in following the instructions, I have never yet been able to get Edge on LON-CL3 to be able to access the Sharepoint site in this lab.  

IExplore.exe is blocked in Step 7, as it should be, but Edge is **also blocked** in Step 6.

I see the 'Enterprise context' listed (in Step 10) exactly as listed: Edge contains the domain name, IExplore shows Personal

I have no problems accessing the same site in Edge/IE in VMs that are not covered by the policy, and am able to access the site from the same VM *before* the policy is in effect.  (i.e., it should not be any other network/firewall mechanism blocking access)

Upgrading to the latest Edge, has no effect. (not that it should, just curious)

AM I missing something?  Is Edge simply supposed to be blocked as well?

**Comment by davemct** [comment]
Just did this lab in class.  EVERYONE'S Edge on LON-CL3 and LON-CL4 is blocked.  Not just the SharePoint site, but even Endpoint.microsoft.com and Bing.com

Restarting does not fix.

I had the students delete the WIP policy and resync both CL3 and CL4 but Edge is still blocked for all urls.

**Comment by DaleMcC** [comment]
This lab has NEVER completed successfully for me or any of my students. Neither IE OR Edge has ever been blocked. 

Dale McCormick

**Comment by BrianHinkelman** [comment]
Thanks for your feedback. The correct result should be that with the WIP applied, IExplorer should not be able to access https://_yourtenant_.sharepoint.com, whereas with Edge, you should be able to access the site. 

We are reviewing this, however, given that there are three different results between three MCTs, issues like this are frequently due to differences in how ALHs implement the lab. Strongly encourage opening a ticket with your ALH, and verifying their implementation does not inadvertently impact this lab, and if no cause can be found for the anomalies, the ALH can open a ticket with Microsoft , and we can work with the ALH to identify the underlying cause.

**Comment by TesterTesterson1004** [comment]
Thanks for looking in to it!  

With regard to the type of issue behavior, and its consistency, I have had a consistently identical experience (Edge always blocked once policy applies, IExplore works) w/LODS since the updates to the instructions were made this summer, but do not have any other experiences w/different ALHs.  I have had the same experience when using my own copies of the VMs in a home lab.

Also at same ALH, before the Instructions updates this summer, I had experienced occasionally the behavior referenced by DaleMcC, although at that time I believe this was as a result of confusion caused by this issue ( https://github.com/MicrosoftLearning/MD-101T00-ManagingModernDesktops/issues/41 ) and/or earlier iterations of how the instructions & Azure worked before Intune/settings/config migrated.

One aspect that may effect repro regardless of ALH or instructions set:  In some cases, Azure is just slow to implement a change - slow to the point of disbelief, in that I have had repros currently where all key configs are in place and yet....they do not take effect in a timely fashion.  Save the lab, go to sleep, start fresh in the morning and...hey presto...they are now in place.  Instructors obviously have seen and understand this, just pointing it out because its a periodic -- and completely unrelated -- variable that can easily effect repro consistency.  

If anyone can point out an ALH where this succeeds consistently, I would love to know -- because then I could compare and contrast local VMs for differences.  I am unaware of what specific local ALH differences would be expected to have an impact on this issue, since all should be using the identical source VMs for the course.  (VM licensing, Win10 versions, patch levels?)

**Comment by BrianHinkelman** [comment]
Thanks for the additional insights.  Sometimes the lab results are susceptible to performance issues - we really try to avoid scenarios that are sensitive to this, but sometimes, it's unavoidable. But if it's a constant issue, we really want to hear about it. 

Also, I don't want to imply that because the ALH might be able to address the issue, the ALH is necessarily "at fault". We test VMs, and send the same VMs to each ALH - but obviously, no two ALHs will have the same infrastructure. Implementations vary (for example, the multitude of ways used to prevent Windows from updating in the middle of class) might inadvertently impact a particular feature.  

We're trying to address this with additional guidance/awareness for the ALHs, but it starts with awareness of the issue. We know that when you're in the middle of a class, the last thing you're thinking about is contacting support, but we certainly appreciate the effort to make the issues known whenever possible.

**Comment by TesterTesterson1004** [comment]
Understood - and thanks again for the ability to post/interact on issues such as this.  This is by no means a 'huge' issue, its just one of those fiddly bits that has been an 'itch' for so long I feel like I am either missing something incredibly simple....or else something devilishly obscure.  :)

**Comment by BrianHinkelman** [comment]
Corrected in Feb 2021 update
