### ISSUE TITLE
Lab 0601, task 2, step 9 - name of tenant

### ISSUE THREAD

**Issue by davemct** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#80]
Instructions say:

9. On the Add network boundary pane, configure the following and then select OK:
Boundary type: Cloud resources
Name: SharePoint online
Value: yourtenant.sharepoint.com

It sounds stupid to ask, but students are actually putting in the value: yourtenant.sharepoint.com.

If you meant to say M365X123456@sharepoint.com, you should use italics on the value, as follows:

9.
Value: _yourtenant.sharepoint.com_

Am I correct?

**Comment by BrianHinkelman** [comment]
Yes, you use the actual tenant name provided in place of _yourtenant_. This is explained in the Introduction of the course.  I believe it's in the intro slides as well.  There are several font/style choices out there that signify "don't actually enter this" or substitutions - we try to keep it plain, so that ALHs, which enable features like auto-fill, are able to support that.
