### ISSUE TITLE
Lab 0502 - AD Sync operation not needed for Password Writeback

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MD-101T00-ManagingModernDesktops#85]
In **Lab 0502, Task 4**, why do we initiate a sync operation? Password writeback does not use sync, it uses the Service Bus and notifications. ([How does self-service password reset writeback work in Azure Active Directory?](https://docs.microsoft.com/en-us/azure/active-directory/authentication/concept-sspr-writeback#how-password-writeback-works)) Putting this here gives the false impression that a sync is needed.

**Comment by ITBlandMCT** [comment]
For that matter, why are we demonstrating a password change instead of sspr? (To reduce time?)

**Comment by craigbeeremct** [comment]
Agreed. Wasn't there a practice on SSPR in this ocourse in the past? Or am I thinking of the Office365 courses (20347, MS-030)?

**Comment by BrianHinkelman** [comment]
Correct, the cmd is not actually needed for SSPR.  Since on-demand labs tend to be somewhat temperamental when it comes to synchronizing, we tend to err on the side of caution and force syncs to just ensure AD is healthy. After review, we agree it does imply the step is required or directly related. We will update the steps to note it's purpose. Thanks for bringing this to our attention.
